---
name: 业务负责人审批
option:
  - describe: 业务审批人
    name: oaapprover
    type: input
    value: ""

template_argv:
  approver: ${oaapprover}
  title:    "BPM/${_bpmuuid_}/注册域名"
  content:  "\n申请人:${_user_}\n域名:${x.domain}\nBPM单号:${_bpmuuid_}\nURL:${_caseurl_}\n申请理由:${x.note}"
  record: 1
  relaxed: 1
  submitter: '${_user_}'
