---
name: '提交人的领导审批'
option:
#  - describe: 业务审批人
#    name: oaapprover
#    type: input
#    value: ""

  - describe: 申请理由
    name: note
    type: text
    value: ""

template_argv:
  approver: "leader(${_user_})"
  title:    "BPM/${_bpmuuid_}/资源申请/腾讯云/CVM"
  content:  "\n申请人:${_user_}\nBPM单号:${_bpmuuid_}\n申请理由:${x.note}"
