---
name: 创建腾讯云cvm
multi: 1
option:
  - name: account
    describe: 云账号
    command: c3mc-display-cloud-account-list qcloud
    type: selectx
    value: ""

  - name: region
    describe: 区域
    rely:
      - account
    command: c3mc-qcloud-cvm-describe-regions | c3mc-bpm-display-field-values Region,RegionName,RegionState
    type: selectx
    value: ""

  - name: zone
    describe: 可用区
    rely:
      - account
      - region
    command: c3mc-qcloud-cvm-describe-zones | c3mc-bpm-display-field-values Zone,ZoneName,ZoneState
    type: selectx
    value: ""

  - name: project_id
    describe: 项目
    rely:
      - account
      - region
    command: c3mc-qcloud-cvm-describe-projects | c3mc-bpm-display-field-values ProjectId,Name
    type: selectx
    value: ""

  - name: charge_type
    describe: 付费方式
    type: select
    option: [ 'PREPAID' ]
    value: "PREPAID"

  - name: instance_config
    describe: 机型
    rely:
      - account
      - region
      - zone
      - charge_type
    command: c3mc-qcloud-cvm-describe-instance-configs | c3mc-bpm-display-field-values InstanceType,Cpu,Memory,Status,Gpu
    type: selectx
    value: ""

  - name: image_id
    describe: 镜像
    rely:
      - account
      - region
    command: c3mc-qcloud-cvm-describe-images | c3mc-bpm-display-field-values ImageId,ImageName,ImageType
    type: selectx
    value: ""

  - name: system_disk_type
    describe: 查询支持的系统盘类型列表
    command: c3mc-qcloud-cvm-describe-system-disk-type-list | c3mc-bpm-display-field-values id,name,size_range
    type: selectx
    value: ""

  - name: system_disk_size
    describe: 系统盘大小(GB)
    type: number
    required: true
    value: ""

  - name: if_need_data_volume
    describe: 是否需要数据盘
    command: c3mc-yes-and-no | c3mc-bpm-display-field-values id,name
    type: selectx
    value: ""

  - name: data_disk_type
    describe: 数据盘类型
    command: c3mc-qcloud-cvm-describe-data-disk-type-list | c3mc-bpm-display-field-values id,name,size_range
    type: selectx
    value: ""
    show: [ 'if_need_data_volume', 'yes' ]
 
  - name: data_disk_size
    describe: 数据盘大小(GB)
    variable_name: data_disk_size
    type: number
    value: ""
    show: [ 'if_need_data_volume', 'yes' ]

  - name: vpc_id
    describe: VPC
    rely:
      - account
      - region
    command: c3mc-qcloud-cvm-describe-vpcs | c3mc-bpm-display-field-values VpcId,VpcName
    type: selectx
    value: ""

  - name: subnet_id
    describe: 子网
    rely:
      - account
      - region
      - vpc_id
      - zone
    command: c3mc-qcloud-cvm-describe-subnets | c3mc-bpm-display-field-values SubnetId,SubnetName,AvailableIpAddressCount
    type: selectx
    value: ""

  - name: security_group_ids
    describe: 安全组
    rely:
      - account
      - region
      - project_id
    command: c3mc-qcloud-cvm-describe-security-groups | c3mc-bpm-display-field-values SecurityGroupId,SecurityGroupName
    type: selectxm
    value: ""

  - name: tag
    describe: 机器标签
    # 格式: "[{\"key\": \"key1\", \"value\": \"value1\"}, {\"key\": \"key2\", \"value\": \"value2\"}]"
    type: kvarray
    value: "[]"

  - name: instance_charge_count
    describe: "购买时长(月)"
    type: number
    value: ""

  - name: renew_flag
    describe: 自动续费方式
    command: c3mc-qcloud-cvm-describe-renew-flag-list | c3mc-bpm-display-field-values id,name
    type: selectx
    value: ""

  - name: instance_name
    describe: 实例名称
    type: input
    value: ""

  - name: internet_charge_type
    describe: 网络计费类型
    command: c3mc-qcloud-cvm-describe-internet-charge-type-list | c3mc-bpm-display-field-values id,name
    type: selectx
    value: ""

  - name: internet_max_bandwidth_out
    describe: "公网出带宽上限(兆)"
    variable_name: internet_max_bandwidth_out
    type: input
    value: ""

template_argv:
  # 账号
  account: ${account}
  # 区域
  region: ${region}
  # 可用区
  zone: ${zone}
  # 项目id
  project_id: ${project_id}
  # 机型型号
  instance_config: ${instance_config}
  # 镜像id
  image_id: ${image_id}
  # 系统盘类型
  system_disk_type: ${system_disk_type}
  # 系统盘大小
  system_disk_size: ${system_disk_size}
  # 是否需要数据盘
  if_need_data_volume: ${if_need_data_volume}
  # 数据盘类型
  data_disk_type: ${data_disk_type}
  # 数据盘大小
  data_disk_size: ${data_disk_size}
  # vpc_id
  vpc_id: ${vpc_id}
  # 子网id
  subnet_id: ${subnet_id}
  # 安全组id列表，多个安全组id用英文逗号分隔
  security_group_ids: ${security_group_ids}
  # 标签
  # 格式: "[{\"key\": \"key1\", \"value\": \"value1\"}, {\"key\": \"key2\", \"value\": \"value2\"}]"
  tag: ${tag}
  # 实例付费方式
  instance_charge_type: ${charge_type}
  # 购买时长
  instance_charge_count: ${instance_charge_count}
  # 自动续费标识
  renew_flag: ${renew_flag}
  # 实例名称
  instance_name: ${instance_name}
  # 网络计费类型
  internet_charge_type: ${internet_charge_type}
  # 公网出带宽上限
  internet_max_bandwidth_out: ${internet_max_bandwidth_out}
