---
name: '业务负责人审批'
option:
  - describe: 业务审批人
    name: oaapprover
    type: input
    value: ""

template_argv:
  approver: ${oaapprover}
  title:    "BPM/${_bpmuuid_}/域名解析/新申请"
  content:  "申请人:${_user_} 域名: ${x.domain} BPM单号: ${_bpmuuid_}"
