---
name: 挂树
option:
  - name:     tree_path
    describe: 服务树
    type:     input
    value:    ""

template_argv:
  tree_path:        ${tree_path}
  instance_ids:     ${var.instance_id}
  type:             'database'
  subtype:          "qcloud-cdb"
  type_code:        "g4"
  extinstance_ids:  ${var.extinstance_id} 
