---
name: '提交人的领导审批'
option:
#  - describe: 业务审批人
#    name: oaapprover
#    type: input
#    value: ""

  - describe: 申请理由
    name: note
    type: text
    value: ""

template_argv:
  approver: "leader(${_user_})"
  title:    "BPM/${_bpmuuid_}/资源申请/AWS/EC2"
  content:  "\n申请人:${_user_}\nBPM单号:${_bpmuuid_}\nURL:${_caseurl_}\n申请理由:${x.note}"
  record: 1
  relaxed: 1
  submitter: '${_user_}'
